default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  host: <%= ENV.fetch('MYSQL_HOST') %>

development:
  <<: *default
  database: datax_dev

test:
  <<: *default
  database: datax_test

production:
  <<: *default
  database: portfilio_prd
  username: app
  password: hoge
